apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
data:
  IVRS_CONFIG_URL: "{{ .Values.ivrs_config_url }}"
  TELEMETRY_API_URL: "{{ .Values.ivrs_telemetry_api_url}}"
  ENV: "{{ .Values.ivrs_env }}"


