namespace: ""
imagepullsecrets: ""
dockerhub: ""

content_repository: contentservice
content_image_tag: latest
content_config_cache_ttl: "1"
content_log_level: "warn"

replicaCount: 1
resources:
  requests:
    cpu: 100m
    memory: 100Mi
  limits:
    cpu: 1
    memory: 1024Mi
network:
  port: 3000
  targetport: 3000
strategy:
  type: RollingUpdate
  maxsurge: 25
  maxunavailable: 25

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 60
  targetMemoryUtilizationPercentage: ""
